packages/secret: drop adding virtualization.vmVariant
It causes recursion error like this:

error: virtualisation.vmVariant*.virtualisation.vmVariant is not supported

Signed-off-by: Jakub Sokołowski <jakub@status.im>